# PyTorch for Beginners

Let's start off by installing PyTorch.

In [28]:
# Use this if you have conda installed
# !conda install -c pytorch pytorch

# Use this if you are on Google Colab
# or don't have conda installed
#!pip3 install torch

In [29]:
import torch

In [30]:
print("torch version : {}".format(torch.__version__))

torch version : 1.12.1


# Introduction to Tensors

Let’s see how we can create a PyTorch Tensor.

In [31]:
# Create a Tensor with just ones in a column
a = torch.ones(3)
# Print the tensor we created
print(a)
 
# Create a Tensor with just zeros in a column
b = torch.zeros(3)
print(b)

tensor([1., 1., 1.])
tensor([0., 0., 0.])


In [32]:
print(a.shape)

torch.Size([3])


In [33]:
print(a.size())

torch.Size([3])


In [34]:
print(a.dtype)

torch.float32


In [35]:
lst=[1.0, 2.0, 3.0, 4.0, 5.0]
c = torch.tensor(lst)
print(c)

tensor([1., 2., 3., 4., 5.])


In [36]:
d = torch.zeros(3,2)
print(d)

e = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(e)

# 3D Tensor
f = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(f)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [37]:
import numpy as np
ary=np.array([[1, 2, 3], [4, 5, 6]])
g=torch.tensor(ary)
print(g)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:

In [38]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y=x[1][2]
print(y)
print(y.type())

tensor(6)
torch.LongTensor


Use torch.Tensor.item() to get a Python number from a tensor containing a single value:

In [39]:
z=y.item()
print(type(z))


<class 'int'>


In [40]:
x[0][1] = 8
print(x)

tensor([[1, 8, 3],
        [4, 5, 6]])


In [41]:
# Similarly for 3D Tensor
print(f[1,0,0])
print(f[1][0][0])
#print(f[1])
#print(f[1][0])

tensor(5.)
tensor(5.)


In [42]:
# All elements
print(f[:])
 
# All elements from index 1 to 2 (inclusive)
print(c[1:3])
 
# All elements till index 4 (exclusive)
print(c[:4])
 
# First row
print(f[0,:])
 
# Second column
print(f[:,1])

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([2., 3.])
tensor([1., 2., 3., 4.])
tensor([[1., 2.],
        [3., 4.]])
tensor([[3., 4.],
        [7., 8.]])


Arithmetic Operations on Tensors

In [43]:
# Create tensor
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[-1,2,-3],[4,-5,6]])
 
# Addition
print(tensor1+tensor2)
# We can also use
print(torch.add(tensor1,tensor2))


tensor([[ 0,  4,  0],
        [ 8,  0, 12]])
tensor([[ 0,  4,  0],
        [ 8,  0, 12]])


In [44]:
# Subtraction
print(tensor1-tensor2)
# We can also use
print(torch.sub(tensor1,tensor2))

tensor([[ 2,  0,  6],
        [ 0, 10,  0]])
tensor([[ 2,  0,  6],
        [ 0, 10,  0]])


In [45]:
 
# Multiplication
# Tensor with Scalar
print(tensor1 * 2)

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [46]:
# Tensor with another tensor
# Elementwise Multiplication
print(tensor1 * tensor2)

tensor([[ -1,   4,  -9],
        [ 16, -25,  36]])


In [47]:
# Matrix multiplication
tensor3 = torch.tensor([[1,2],[3,4],[5,6]])
print(torch.mm(tensor1,tensor3))

tensor([[22, 28],
        [49, 64]])


In [48]:
# Division
# Tensor with scalar
print(tensor1//2)

tensor([[0, 1, 1],
        [2, 2, 3]])


C:\Users\SHMY1088\AppData\Local\Temp\ipykernel_10336\552990665.py:3: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  print(tensor1//2)


In [49]:
# Tensor with another tensor
# Elementwise division
print(tensor1//tensor2)

tensor([[-1,  1, -1],
        [ 1, -1,  1]])


C:\Users\SHMY1088\AppData\Local\Temp\ipykernel_10336\765121839.py:3: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  print(tensor1//tensor2)


CPU v/s GPU Tensor

In [50]:
# Create a tensor for CPU
# This will occupy CPU RAM
tensor_cpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cpu')
 
# Create a tensor for GPU
# This will occupy GPU RAM
#tensor_gpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cuda')

Attributes of a Tensor

In [51]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

r2 = torch.rand(2, 2)
print('\nA different random tensor:')
print(r2) # new values

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\nShould match r1:')
print(r3) # repeats values of r1 because of re-seed