In [139]:
# Import required libraries:
import numpy as np# Define input features:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print (input_features.shape)
print (input_features)

(4, 2)
[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [140]:
# Define target output:
target_output = np.array([[0,0,0,1]])# Reshaping our target output into vector:
y = target_output.reshape(4,1)
print(y.shape)

(4, 1)


In [141]:
print (target_output)# Define weights:
W = np.array([[0.1],[0.2]])
print(W.shape)
print (W)

[[0 0 0 1]]
(2, 1)
[[0.1]
 [0.2]]


In [142]:
b = 0.3# Bias weight:
lr = 0.05# Learning Rate:

In [143]:
#Sigmoid Function
def sigmoid(x):
    return 1/(1+np.exp(-x))# Derivative of sigmoid function:
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))# Main logic for neural network:

In [144]:
# Running our code 10000 times:for epoch in range(10000):
X = input_features#Feedforward input:
Z = np.dot(X, W) + b #Feedforward output:
print(Z)
a = sigmoid(Z) #Backpropogation
print(a)

[[0.3]
 [0.5]
 [0.4]
 [0.6]]
[[0.57444252]
 [0.62245933]
 [0.59868766]
 [0.64565631]]


In [145]:
#Calculating error
error = (a - y)
error_sqr = (a - y)**2
#Going with the formula:
C = 0.5*(error_sqr.sum())
print(C)

0.6007130959048217


In [146]:
#Calculating derivative:
dC_da= error
print(dC_da)
print(dC_da.shape)
da_dZ = sigmoid_der(Z)
print(da_dZ)
print(da_dZ.shape)

[[ 0.57444252]
 [ 0.62245933]
 [ 0.59868766]
 [-0.35434369]]
(4, 1)
[[0.24445831]
 [0.23500371]
 [0.24026075]
 [0.22878424]]
(4, 1)


size od dC_da & da_dZ matrix are 4,1
size ow weight matrix = 2,1
multiplication matrix size= (2,4)*(4,1)= (2,1)

In [147]:
#Multiplying individual derivatives:
deriv = dC_da * da_dZ #Multiplying with the 3rd individual derivative:
print(deriv)
#Finding the transpose of input_features:
dZ_dw = input_features.T
print(dZ_dw)
print(dZ_dw.shape)
dC_dw = np.dot(dZ_dw,deriv)
print(dC_dw)
print(dC_dw.shape)

[[ 0.14042725]
 [ 0.14628025]
 [ 0.14384114]
 [-0.08106825]]
[[0 0 1 1]
 [0 1 0 1]]
(2, 4)
[[0.06277289]
 [0.065212  ]]
(2, 1)


In [148]:
#Updating the weights values:
W -= lr * dC_dw #Updating the bias weight value:
print(W)
print(W.shape)
for i in deriv:
    bias -= lr * i #Check the final values for weight and biasprint (weights)


[[0.09686136]
 [0.1967394 ]]
(2, 1)


In [152]:
single_point = np.array([1,0]) #1st step:
result1 = np.dot(single_point, weights) + bias #2nd step:
result2 = sigmoid(result1) #Print final result
print(result2) #Taking inputs:
single_point = np.array([1,1]) #1st step:
result1 = np.dot(single_point, weights) + bias #2nd step:
result2 = sigmoid(result1) #Print final result
print(result2) #Taking inputs:
single_point = np.array([0,0]) #1st step:
result1 = np.dot(single_point, weights) + bias #2nd step:
result2 = sigmoid(result1) #Print final result
print(result2)

[0.23103229]
[0.58062168]
[0.62695495]
[0.55750253]
